-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    admin_email character varying COLLATE pg_catalog."default" NOT NULL,
    admin_password character varying COLLATE pg_catalog."default" NOT NULL,
    admin_firstname character varying COLLATE pg_catalog."default" NOT NULL,
    admin_lastname character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (admin_email)
    );

CREATE TABLE IF NOT EXISTS public.customer
(
    email character varying COLLATE pg_catalog."default" NOT NULL,
    firstname character varying COLLATE pg_catalog."default" NOT NULL,
    lastname character varying COLLATE pg_catalog."default" NOT NULL,
    address character varying COLLATE pg_catalog."default" NOT NULL,
    postal_code integer NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (email)
    );

CREATE TABLE IF NOT EXISTS public.customer_order
(
    customer_order_id serial NOT NULL,
    customer_email character varying COLLATE pg_catalog."default" NOT NULL,
    order_status character varying COLLATE pg_catalog."default" NOT NULL,
    roof_type_id integer NOT NULL,
    width_mm integer NOT NULL,
    length_mm integer NOT NULL,
    height_mm integer NOT NULL,
    shed_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    order_price numeric(10, 2) NOT NULL,
    CONSTRAINT customer_order_pkey PRIMARY KEY (customer_order_id)
    );

CREATE TABLE IF NOT EXISTS public.customer_order_change
(
    customer_order_change_id serial NOT NULL,
    customer_order_id integer NOT NULL,
    admin_email character varying COLLATE pg_catalog."default" NOT NULL,
    admin_note character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT customer_order_change_pkey PRIMARY KEY (customer_order_change_id)
    );

CREATE TABLE IF NOT EXISTS public.material_category
(
    material_category_id serial NOT NULL,
    material_category_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT material_category_pkey PRIMARY KEY (material_category_id)
    );

CREATE TABLE IF NOT EXISTS public.material_product
(
    material_product_id serial NOT NULL,
    material_category_id integer NOT NULL,
    unit_id integer NOT NULL,
    length_mm integer,
    material_product_name character varying COLLATE pg_catalog."default" NOT NULL,
    material_product_description text COLLATE pg_catalog."default" NOT NULL,
    material_price numeric(10, 2) NOT NULL,
    CONSTRAINT material_product_pkey PRIMARY KEY (material_product_id)
    );

CREATE TABLE IF NOT EXISTS public.order_material
(
    order_material_id serial NOT NULL,
    customer_order_id integer NOT NULL,
    material_product_id integer NOT NULL,
    quantity integer NOT NULL,
    note text COLLATE pg_catalog."default",
    total_price numeric(10, 2) NOT NULL,
    CONSTRAINT order_material_pkey PRIMARY KEY (order_material_id)
    );

CREATE TABLE IF NOT EXISTS public.roof_type
(
    roof_type_id serial NOT NULL,
    roof_type_name character varying COLLATE pg_catalog."default" NOT NULL,
    roof_type_deg integer NOT NULL,
    roof_type_price numeric(10, 2) NOT NULL,
    CONSTRAINT roof_type_pkey PRIMARY KEY (roof_type_id)
    );

CREATE TABLE IF NOT EXISTS public.shed
(
    shed_id serial NOT NULL,
    shed_width_mm integer NOT NULL,
    shed_length_mm integer NOT NULL,
    CONSTRAINT shed_pkey PRIMARY KEY (shed_id)
    );

CREATE TABLE IF NOT EXISTS public.unit
(
    unit_id serial NOT NULL,
    unit_name character varying COLLATE pg_catalog."default" NOT NULL,
    unit_short_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT unit_pkey PRIMARY KEY (unit_id)
    );

ALTER TABLE IF EXISTS public.customer_order
    ADD CONSTRAINT customer_order_customer_fkey FOREIGN KEY (customer_email)
    REFERENCES public.customer (email) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_order
    ADD CONSTRAINT customer_order_roof_type_fkey FOREIGN KEY (roof_type_id)
    REFERENCES public.roof_type (roof_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_order
    ADD CONSTRAINT customer_order_shed_fkey FOREIGN KEY (shed_id)
    REFERENCES public.shed (shed_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_order_change
    ADD CONSTRAINT customer_order_change_admin_fkey FOREIGN KEY (admin_email)
    REFERENCES public.admin (admin_email) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer_order_change
    ADD CONSTRAINT customer_order_change_order_fkey FOREIGN KEY (customer_order_id)
    REFERENCES public.customer_order (customer_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.material_product
    ADD CONSTRAINT material_product_category_fkey FOREIGN KEY (material_category_id)
    REFERENCES public.material_category (material_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.material_product
    ADD CONSTRAINT material_product_unit_fkey FOREIGN KEY (unit_id)
    REFERENCES public.unit (unit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_material
    ADD CONSTRAINT order_material_order_fkey FOREIGN KEY (customer_order_id)
    REFERENCES public.customer_order (customer_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_material
    ADD CONSTRAINT order_material_product_fkey FOREIGN KEY (material_product_id)
    REFERENCES public.material_product (material_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;