BEGIN;

-- Kategorier
INSERT INTO material_category (material_category_name) VALUES
                                                           ('Træ og Tagplader'),   -- kan bruges til andet træ generelt hvis du vil
                                                           ('Beslag og Skruer'),
                                                           ('Stolper'),
                                                           ('Rem/Spær'),
                                                           ('Understern'),
                                                           ('Overstern'),
                                                           ('Beklædning'),
                                                           ('Vandbræt'),
                                                           ('Tagplader'),
                                                           ('Løsholter'),
                                                           ('Lægter');

-- Enheder
INSERT INTO unit (unit_name, unit_short_name) VALUES
                                                  ('Styk',  'Stk'),
                                                  ('Pakke', 'Pakke'),
                                                  ('Rulle', 'Rulle'),
                                                  ('Sæt',   'Sæt');

INSERT INTO roof_type (roof_type_name, roof_type_deg, roof_type_price) VALUES
                                                                           ('Fladt tag', 0, 0.00),
                                                                           ('5°', 5, 1200.00),
                                                                           ('10°', 10, 2400.00),
                                                                           ('15°', 15, 3600.00),
                                                                           ('20°', 20, 4800.00),
                                                                           ('25°', 25, 6000.00),
                                                                           ('30°', 30, 7200.00),
                                                                           ('35°', 35, 8400.00),
                                                                           ('40°', 40, 9600.00),
                                                                           ('45°', 45, 10800.00);

-- Materialer
INSERT INTO material_product
(material_category_id, unit_id, length_mm,
 material_product_name, material_product_description, material_price)
VALUES
    -- UNDERSTERN
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 146.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 171.21),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 205.59),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 234.95),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 264.33),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Understern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     600, '25x200 mm. trykimp. Brædt', 'understernbrædder til for & bag ende og/el. side.', 335.70),

    -- OVERSTERN
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 104.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 125.81),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 146.79),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 167.75),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 188.73),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Overstern'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     600, '25x125mm. trykimp. Brædt', 'oversternbrædder til forenden og/el. siderne', 161.70),

    -- LÆGTER (til bagside af dør)
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 50.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     330, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 55.93),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 61.01),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     390, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 66.10),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 71.19),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     450, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 76.28),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 81.35),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     500, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 84.75),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     510, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 86.44),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Lægter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '38x73 mm. Lægte ubh.', 'til 2 på bagside af dør', 91.53),

    -- LØSHOLTER (reglar)
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     240, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 47.88),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     270, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 53.86),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 59.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     330, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 65.83),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 71.81),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     390, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 77.80),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 83.79),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     450, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 89.78),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 95.75),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     510, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 101.74),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Løsholter'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '45x95 mm. Reglar ub.', 'løsholter til skur gavle og/el. sider', 107.73),

    -- REM / SPÆR
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 158.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 190.61),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 222.39),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 254.15),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 285.93),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     600, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 479.70),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     660, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 527.66),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Rem/Spær'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     720, '45x195 mm. spærtræ ubh.', 'Remme i sider, saddles ned i stolper (skur del, deles) og/el. spær, monteres på rem', 575.64),

    -- STOLPER
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     180, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 82.70),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     210, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 96.49),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     240, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 110.28),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     270, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 124.06),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 137.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 165.41),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 192.99),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Stolper'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '97x97 mm. trykimp. Stolpe', 'Stolper nedgraves 90 cm. i jord', 220.55),

    -- BEKLÆDNING (skur)
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     180, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 19.70),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     210, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 22.99),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     240, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 26.28),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     270, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 29.56),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 32.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 39.41),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beklædning'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '19x100 mm. trykimp. Brædt SEKSTA', 'til beklædning af skur 1 på 2', 45.99),

    -- VANDBRÆDT
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Vandbræt'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, '19x100 mm. trykimp. Brædt KVINTA', 'vandbrædt på stern i sider og/el. forende', 53.85),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Vandbræt'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, '19x100 mm. trykimp. Brædt KVINTA', 'vandbrædt på stern i sider og/el. forende', 64.61),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Vandbræt'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, '19x100 mm. trykimp. Brædt KVINTA', 'vandbrædt på stern i sider og/el. forende', 75.39),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Vandbræt'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, '19x100 mm. trykimp. Brædt KVINTA', 'vandbrædt på stern i sider og/el. forende', 86.15),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Vandbræt'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     540, '19x100 mm. trykimp. Brædt KVINTA', 'vandbrædt på stern i sider og/el. forende', 96.93),

    -- TAGPLADER
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     240, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 139.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     300, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 179.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     360, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 199.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     420, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 239.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     480, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 269.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Tagplader'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     600, 'Plastmo Ecolite blåtonet', 'tagplader monteres på spær', 339.00),

    -- Beslag og Skruer (som før)
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Pakke'),
     NULL, 'plastmo bundskruer 200 stk.', 'Skruer til tagplader', 429.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Rulle'),
     NULL, 'huldbånd 1x20 mm. 10 mtr.', 'Til vindkryds på spær', 319.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 'universal 190 mm højre', 'Til montering af spær på rem', 30.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 'universal 190 mm venstre', 'Til montering af spær på rem', 22.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Pakke'),
     NULL, '4,5 x 60 mm. skruer 200 stk.', 'Til montering af stern & vandbrædt', 249.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Pakke'),
     NULL, '4,0 x 50 mm. beslagskruer 250 stk.', 'Til montering af universalbeslag + huldånd', 319.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 'bræddebolt 10 x 120 mm', 'Til montering af rem på stolper', 29.33),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 'firkantskiver 40x40x11mm', 'Til montering af rem på stolper', 15.71),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Pakke'),
     NULL, '4,5 x 70 mm. Skruer 400 stk.', 'Til montering af yderste beklædning', 175.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Pakke'),
     NULL, '4,5 x 50 mm. Skruer 300 stk.', 'Til montering af inderste beklædning', 149.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Sæt'),
     NULL, 'stalldørsgreb 50x75', 'Til lås på dør i skur', 269.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 't hængsel 390 mm', 'Til skurdør', 139.00),
    ((SELECT material_category_id FROM material_category WHERE material_category_name='Beslag og Skruer'),
     (SELECT unit_id FROM unit WHERE unit_short_name='Stk'),
     NULL, 'vinkelbeslag 35', 'Til montering af løsholter i skur', 199.00);

COMMIT;
