@startuml
[*] --> homepage
[*] --> adminLogin

homepage --> tailorMadeCarport
homepage --> preMadeCarport

tailorMadeCarport --> carportWithFlatRoof
tailorMadeCarport --> carportWithAngledRoof

carportWithFlatRoof --> setCarportWidth : Choose the carports width
carportWithFlatRoof --> setCarportLength : Choose the carports Length
carportWithFlatRoof --> chooseCarportWithShed : Choose if the carport has shed
chooseCarportWithShed --> shedWidth : If chooseCarportWithShed = true then choose shedWidth
chooseCarportWithShed --> shedLength : If chooseCarportWithShed = true then choose shedLength
carportWithFlatRoof --> setSurname : Give surname
carportWithFlatRoof --> setLastname : Give lastname
carportWithFlatRoof --> setAddress : Give address
carportWithFlatRoof --> setPostalcode : Give postalcode
carportWithFlatRoof --> setEmail : Give email

setCarportWidth --> carportWithFlatRoof : sets carportsWidth
setCarportLength --> carportWithFlatRoof : sets carportsLength
chooseCarportWithShed --> carportWithFlatRoof : sets carportWithShed to true
shedWidth --> carportWithFlatRoof : sets shedWidth
shedLength --> carportWithFlatRoof : sets shedWLength
setSurname --> carportWithFlatRoof : sets surname
setLastname --> carportWithFlatRoof : sets lastname
setAddress --> carportWithFlatRoof : sets address
setPostalcode --> carportWithFlatRoof : sets postalcode
setEmail --> carportWithFlatRoof : sets email

carportWithFlatRoof ---> sendOrder : Send order request if all the fields have been set
sendOrder --> carportWithFlatRoof : If order fields did not have the correct information
sendOrder --> createNewOrder : Creates new order
createNewOrder --> sendEmailOfRequestedCarport : Sends an email of the requested carport to the user
createNewOrder --> homepage : Redirect to homepage


carportWithAngledRoof --> setCarportWidthAngledRoof : Choose the carports width
carportWithAngledRoof --> setCarportLengthAngledRoof : Choose the carports Length
carportWithAngledRoof --> chooseCarportWithShedAngledRoof : Choose if the carport has shed
carportWithAngledRoof --> shedWidthAngledRoof : If chooseCarportWithShed = true then choose shedWidth
carportWithAngledRoof --> shedLengthAngledRoof : If chooseCarportWithShed = true then choose shedLength
carportWithAngledRoof --> setSurnameAngledRoof : Give surname
carportWithAngledRoof --> setLastnameAngledRoof : Give lastname
carportWithAngledRoof --> setAddressAngledRoof : Give address
carportWithAngledRoof --> setPostalcodeAngledRoof : Give postalcode
carportWithAngledRoof --> setEmailAngledRoof : Give email

setCarportWidthAngledRoof --> carportWithAngledRoof : sets carportsWidth
setCarportLengthAngledRoof --> carportWithAngledRoof : sets carportsLength
chooseCarportWithShedAngledRoof --> carportWithAngledRoof : sets carportWithShed to true
shedWidthAngledRoof --> carportWithAngledRoof : sets shedWidth
shedLengthAngledRoof --> carportWithAngledRoof : sets shedWLength
setSurnameAngledRoof --> carportWithAngledRoof : sets surname
setLastnameAngledRoof --> carportWithAngledRoof : sets lastname
setAddressAngledRoof --> carportWithAngledRoof : sets address
setPostalcodeAngledRoof --> carportWithAngledRoof : sets postalcode
setEmailAngledRoof --> carportWithAngledRoof : sets email

carportWithAngledRoof ---> sendOrder : Send order request if all the fields have been set
sendOrder --> carportWithAngledRoof : If order fields did not have the correct information
sendOrder --> createNewOrder : Creates new order
createNewOrder --> sendEmailOfRequestedCarport : Sends an email of the requested carport to the user
createNewOrder --> homepage : Redirect to homepage


adminLogin --> adminDashboard : If login true then redirect to adminDashboard
adminDashboard --> adminLogin : Logout
adminDashboard --> adminLogin : Wrong login

adminDashboard --> sortAfterAllPending : Shows all pending orders
adminDashboard --> sortAfterAllRejected : Shows all rejected orders
adminDashboard --> sortAfterAllPaid : Shows all paid orders
adminDashboard --> sortAfterAllAdjusted : Shows all adjusted orders

adminDashboard --> showOrder : Clicks on a given order to view it
showOrder --> setPriceOfGivenOrder : Sets a price for the order
showOrder --> sendOrderWithChangedPrice : Sets the new price on the order
sendOrderWithChangedPrice --> sendEmail : Sends email to customer with the given price for the carport

preMadeCarport --> FOGDomain
@enduml